server:
  port: 8090

spring:
  application:
    name: snd-gateway
  profiles:
    active: local
  data:
    redis:
      host: localhost

  cloud:
    nacos:
      config:
        server-addr: localhost:8848
        data-id: snd-gateway
        file-extension: json
        group: DEFAULT_GROUP
        namespace:

      discovery:
        server-addr: localhost:8848
        group: DEFAULT_GROUP
        register-enabled: true

    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

auth:
  token:
    secret-key: qLuRTgBMSKSSPA23WXVSTiH87epblwmH


snd:
  webclient:
    #url: http://localhost:8081
    server-name: snd-user
    enable-logging: true
    
